const simpul = {
  abbreviationtonumber: require("./abbreviationtonumber"),
  base64: require("./base64"),
  batchify: require("./batchify"),
  capitalize: require("./capitalize"),
  changecase: require("./changecase"),
  changeindex: require("./changeindex"),
  clone: require("./clone"),
  clonedeep: require("./clonedeep"),
  copytext: require("./copytext"),
  countlabel: require("./countlabel"),
  date: require("./date"),
  datestring: require("./datestring"),
  delimiter: require("./delimiter"),
  endswith: require("./endswith"),
  escaper: require("./escaper"),
  flatten: require("./flatten"),
  generalcount: require("./generalcount"),
  isEnv: require("./isEnv"),
  jwt: require("./jwt"),
  keychange: require("./keychange"),
  log: require("./log"),
  math: require("./math"),
  noop: require("./noop"),
  numberstring: require("./numberstring"),
  objectKeyGroup: require("./objectKeyGroup"),
  ordinalized: require("./ordinalized"),
  paginationProps: require("./paginationProps"),
  parseCommafiedNumber: require("./parseCommafiedNumber"),
  parsejson: require("./parsejson"),
  recursively: require("./recursively"),
  reduceobject: require("./reduceobject"),
  removeArrayItems: require("./removeArrayItems"),
  removeNullValues: require("./removeNullValues"),
  removePunctuation: require("./removePunctuation"),
  removeStrings: require("./removeStrings"),
  replaceStrings: require("./replaceStrings"),
  sentimentemoji: require("./sentimentemoji"),
  shuffle: require("./shuffle"),
  stringlength: require("./stringlength"),
  stringnumber: require("./stringnumber"),
  stringtest: require("./stringtest"),
  support: require("./support"),
  timenvlog: require("./timenvlog"),
  tokenize: require("./tokenize"),
  trim: require("./trim"),
  trimBoundary: require("./trimBoundary"),
  trimPunctuation: require("./trimPunctuation"),
  tryasync: require("./tryasync"),
  trycallback: require("./trycallback"),
  uid: require("./uid"),
  urlBase64ToUint8Array: require("./urlBase64ToUint8Array"),
  ...require("./validate"),
};

module.exports = simpul;
